# Generated by Django 4.2.4 on 2023-08-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.CharField(default=2, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tittle',
            field=models.IntegerField(default=0),
        ),
    ]
