# Generated by Django 4.2.4 on 2023-08-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_teacher_photo_alter_teacher_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.CharField(max_length=20),
        ),
    ]
