# Generated by Django 4.2.4 on 2023-08-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.CharField(max_length=50),
        ),
    ]
